name: Run CI
description: Run CI checks (lint, typecheck and test)

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    name: ${{ matrix.check.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - name: Lint
            command: npm run lint
          - name: Typecheck
            command: npm run typecheck
          - name: Test
            command: npm run test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Run ${{ matrix.check.name }}
        run: ${{ matrix.check.command }}
